name: Deploy to Cloud Run

on:
  workflow_dispatch:  # 手動トリガーのみ有効化

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker gcr.io

      - name: Build and push Docker image to Google Container Registry
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/field-worker-service:latest field_worker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/field-worker-service:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy field-worker-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/field-worker-service:latest \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated